#!/usr/bin/env bash
set -eux

MODULE=dotenv
JITPACK_URL=https://jitpack.io/com/github/$TRAVIS_REPO_SLUG

test -f ~/.asdf/asdf.sh && source ~/.asdf/asdf.sh

case "$*" in

 "") 
  $0 install
  $0 test
 ;;

 jitpack)
   mill -i $MODULE.m2
   mkdir -p ~/.m2
   cp -rv out/$MODULE/m2/dest/ ~/.m2/repository
 ;;

 "jitpack build")
   curl -fL $JITPACK_URL/$TRAVIS_COMMIT/build.log
 ;;

 "asdf install")
   git clone https://github.com/asdf-vm/asdf.git ~/.asdf
   source ~/.asdf/asdf.sh
   cat .tool-versions | cut -d' ' -f 1 | xargs -IX asdf plugin-add X
   asdf install
 ;;

 install)
   mill $MODULE.publishLocal
 ;;

 test)
   mill $MODULE.tests
   (cd example; mill hello.run)
   (cd example; mill hello.tests)
 ;;
  
esac
